//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FalatGTSModel", "FK_TA_BaseTrafic_TA_Person", "TA_Person", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AtlasTrafficReader.TA_Person), "TA_BaseTraffic", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AtlasTrafficReader.TA_BaseTraffic), true)]
[assembly: EdmRelationshipAttribute("FalatGTSModel", "FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AtlasTrafficReader.TA_Person), "TA_Calculation_Flag_Persons", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AtlasTrafficReader.TA_Calculation_Flag_Persons), true)]

#endregion

namespace AtlasTrafficReader
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FalatGTSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FalatGTSEntities object using the connection string found in the 'FalatGTSEntities' section of the application configuration file.
        /// </summary>
        public FalatGTSEntities() : base("name=FalatGTSEntities", "FalatGTSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FalatGTSEntities object.
        /// </summary>
        public FalatGTSEntities(string connectionString) : base(connectionString, "FalatGTSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FalatGTSEntities object.
        /// </summary>
        public FalatGTSEntities(EntityConnection connection) : base(connection, "FalatGTSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TA_BaseTraffic> TA_BaseTraffic
        {
            get
            {
                if ((_TA_BaseTraffic == null))
                {
                    _TA_BaseTraffic = base.CreateObjectSet<TA_BaseTraffic>("TA_BaseTraffic");
                }
                return _TA_BaseTraffic;
            }
        }
        private ObjectSet<TA_BaseTraffic> _TA_BaseTraffic;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TA_Calculation_Flag_Persons> TA_Calculation_Flag_Persons
        {
            get
            {
                if ((_TA_Calculation_Flag_Persons == null))
                {
                    _TA_Calculation_Flag_Persons = base.CreateObjectSet<TA_Calculation_Flag_Persons>("TA_Calculation_Flag_Persons");
                }
                return _TA_Calculation_Flag_Persons;
            }
        }
        private ObjectSet<TA_Calculation_Flag_Persons> _TA_Calculation_Flag_Persons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TA_Person> TA_Person
        {
            get
            {
                if ((_TA_Person == null))
                {
                    _TA_Person = base.CreateObjectSet<TA_Person>("TA_Person");
                }
                return _TA_Person;
            }
        }
        private ObjectSet<TA_Person> _TA_Person;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TA_NeedUpdateCFP> TA_NeedUpdateCFP
        {
            get
            {
                if ((_TA_NeedUpdateCFP == null))
                {
                    _TA_NeedUpdateCFP = base.CreateObjectSet<TA_NeedUpdateCFP>("TA_NeedUpdateCFP");
                }
                return _TA_NeedUpdateCFP;
            }
        }
        private ObjectSet<TA_NeedUpdateCFP> _TA_NeedUpdateCFP;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TA_BaseTraffic EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTA_BaseTraffic(TA_BaseTraffic tA_BaseTraffic)
        {
            base.AddObject("TA_BaseTraffic", tA_BaseTraffic);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TA_Calculation_Flag_Persons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTA_Calculation_Flag_Persons(TA_Calculation_Flag_Persons tA_Calculation_Flag_Persons)
        {
            base.AddObject("TA_Calculation_Flag_Persons", tA_Calculation_Flag_Persons);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TA_Person EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTA_Person(TA_Person tA_Person)
        {
            base.AddObject("TA_Person", tA_Person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TA_NeedUpdateCFP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTA_NeedUpdateCFP(TA_NeedUpdateCFP tA_NeedUpdateCFP)
        {
            base.AddObject("TA_NeedUpdateCFP", tA_NeedUpdateCFP);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="prsID">No Metadata Documentation available.</param>
        /// <param name="date">No Metadata Documentation available.</param>
        public int UpdateCFP(Nullable<global::System.Decimal> prsID, Nullable<global::System.DateTime> date)
        {
            ObjectParameter prsIDParameter;
            if (prsID.HasValue)
            {
                prsIDParameter = new ObjectParameter("prsID", prsID);
            }
            else
            {
                prsIDParameter = new ObjectParameter("prsID", typeof(global::System.Decimal));
            }
    
            ObjectParameter dateParameter;
            if (date.HasValue)
            {
                dateParameter = new ObjectParameter("Date", date);
            }
            else
            {
                dateParameter = new ObjectParameter("Date", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction("UpdateCFP", prsIDParameter, dateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="date">No Metadata Documentation available.</param>
        public int spr_UpdateCFP_ByTable(Nullable<global::System.DateTime> date)
        {
            ObjectParameter dateParameter;
            if (date.HasValue)
            {
                dateParameter = new ObjectParameter("Date", date);
            }
            else
            {
                dateParameter = new ObjectParameter("Date", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction("spr_UpdateCFP_ByTable", dateParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FalatGTSModel", Name="TA_BaseTraffic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TA_BaseTraffic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TA_BaseTraffic object.
        /// </summary>
        /// <param name="basicTraffic_ID">Initial value of the BasicTraffic_ID property.</param>
        /// <param name="basicTraffic_PrecardId">Initial value of the BasicTraffic_PrecardId property.</param>
        /// <param name="basicTraffic_Date">Initial value of the BasicTraffic_Date property.</param>
        /// <param name="basicTraffic_Time">Initial value of the BasicTraffic_Time property.</param>
        public static TA_BaseTraffic CreateTA_BaseTraffic(global::System.Decimal basicTraffic_ID, global::System.Decimal basicTraffic_PrecardId, global::System.DateTime basicTraffic_Date, global::System.Int32 basicTraffic_Time)
        {
            TA_BaseTraffic tA_BaseTraffic = new TA_BaseTraffic();
            tA_BaseTraffic.BasicTraffic_ID = basicTraffic_ID;
            tA_BaseTraffic.BasicTraffic_PrecardId = basicTraffic_PrecardId;
            tA_BaseTraffic.BasicTraffic_Date = basicTraffic_Date;
            tA_BaseTraffic.BasicTraffic_Time = basicTraffic_Time;
            return tA_BaseTraffic;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BasicTraffic_ID
        {
            get
            {
                return _BasicTraffic_ID;
            }
            set
            {
                if (_BasicTraffic_ID != value)
                {
                    OnBasicTraffic_IDChanging(value);
                    ReportPropertyChanging("BasicTraffic_ID");
                    _BasicTraffic_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BasicTraffic_ID");
                    OnBasicTraffic_IDChanged();
                }
            }
        }
        private global::System.Decimal _BasicTraffic_ID;
        partial void OnBasicTraffic_IDChanging(global::System.Decimal value);
        partial void OnBasicTraffic_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BasicTraffic_PrecardId
        {
            get
            {
                return _BasicTraffic_PrecardId;
            }
            set
            {
                OnBasicTraffic_PrecardIdChanging(value);
                ReportPropertyChanging("BasicTraffic_PrecardId");
                _BasicTraffic_PrecardId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_PrecardId");
                OnBasicTraffic_PrecardIdChanged();
            }
        }
        private global::System.Decimal _BasicTraffic_PrecardId;
        partial void OnBasicTraffic_PrecardIdChanging(global::System.Decimal value);
        partial void OnBasicTraffic_PrecardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BasicTraffic_PersonID
        {
            get
            {
                return _BasicTraffic_PersonID;
            }
            set
            {
                OnBasicTraffic_PersonIDChanging(value);
                ReportPropertyChanging("BasicTraffic_PersonID");
                _BasicTraffic_PersonID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_PersonID");
                OnBasicTraffic_PersonIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _BasicTraffic_PersonID;
        partial void OnBasicTraffic_PersonIDChanging(Nullable<global::System.Decimal> value);
        partial void OnBasicTraffic_PersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BasicTraffic_Date
        {
            get
            {
                return _BasicTraffic_Date;
            }
            set
            {
                OnBasicTraffic_DateChanging(value);
                ReportPropertyChanging("BasicTraffic_Date");
                _BasicTraffic_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_Date");
                OnBasicTraffic_DateChanged();
            }
        }
        private global::System.DateTime _BasicTraffic_Date;
        partial void OnBasicTraffic_DateChanging(global::System.DateTime value);
        partial void OnBasicTraffic_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BasicTraffic_Time
        {
            get
            {
                return _BasicTraffic_Time;
            }
            set
            {
                OnBasicTraffic_TimeChanging(value);
                ReportPropertyChanging("BasicTraffic_Time");
                _BasicTraffic_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_Time");
                OnBasicTraffic_TimeChanged();
            }
        }
        private global::System.Int32 _BasicTraffic_Time;
        partial void OnBasicTraffic_TimeChanging(global::System.Int32 value);
        partial void OnBasicTraffic_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> BasicTraffic_Used
        {
            get
            {
                return _BasicTraffic_Used;
            }
            set
            {
                OnBasicTraffic_UsedChanging(value);
                ReportPropertyChanging("BasicTraffic_Used");
                _BasicTraffic_Used = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_Used");
                OnBasicTraffic_UsedChanged();
            }
        }
        private Nullable<global::System.Boolean> _BasicTraffic_Used;
        partial void OnBasicTraffic_UsedChanging(Nullable<global::System.Boolean> value);
        partial void OnBasicTraffic_UsedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> BasicTraffic_Active
        {
            get
            {
                return _BasicTraffic_Active;
            }
            set
            {
                OnBasicTraffic_ActiveChanging(value);
                ReportPropertyChanging("BasicTraffic_Active");
                _BasicTraffic_Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_Active");
                OnBasicTraffic_ActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _BasicTraffic_Active;
        partial void OnBasicTraffic_ActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnBasicTraffic_ActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> BasicTraffic_Manual
        {
            get
            {
                return _BasicTraffic_Manual;
            }
            set
            {
                OnBasicTraffic_ManualChanging(value);
                ReportPropertyChanging("BasicTraffic_Manual");
                _BasicTraffic_Manual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_Manual");
                OnBasicTraffic_ManualChanged();
            }
        }
        private Nullable<global::System.Boolean> _BasicTraffic_Manual;
        partial void OnBasicTraffic_ManualChanging(Nullable<global::System.Boolean> value);
        partial void OnBasicTraffic_ManualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> BasicTraffic_State
        {
            get
            {
                return _BasicTraffic_State;
            }
            set
            {
                OnBasicTraffic_StateChanging(value);
                ReportPropertyChanging("BasicTraffic_State");
                _BasicTraffic_State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_State");
                OnBasicTraffic_StateChanged();
            }
        }
        private Nullable<global::System.Boolean> _BasicTraffic_State;
        partial void OnBasicTraffic_StateChanging(Nullable<global::System.Boolean> value);
        partial void OnBasicTraffic_StateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BasicTraffic_ReportsListId
        {
            get
            {
                return _BasicTraffic_ReportsListId;
            }
            set
            {
                OnBasicTraffic_ReportsListIdChanging(value);
                ReportPropertyChanging("BasicTraffic_ReportsListId");
                _BasicTraffic_ReportsListId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_ReportsListId");
                OnBasicTraffic_ReportsListIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _BasicTraffic_ReportsListId;
        partial void OnBasicTraffic_ReportsListIdChanging(Nullable<global::System.Decimal> value);
        partial void OnBasicTraffic_ReportsListIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BasicTraffic_OperatorPersonID
        {
            get
            {
                return _BasicTraffic_OperatorPersonID;
            }
            set
            {
                OnBasicTraffic_OperatorPersonIDChanging(value);
                ReportPropertyChanging("BasicTraffic_OperatorPersonID");
                _BasicTraffic_OperatorPersonID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_OperatorPersonID");
                OnBasicTraffic_OperatorPersonIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _BasicTraffic_OperatorPersonID;
        partial void OnBasicTraffic_OperatorPersonIDChanging(Nullable<global::System.Decimal> value);
        partial void OnBasicTraffic_OperatorPersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BasicTraffic_Description
        {
            get
            {
                return _BasicTraffic_Description;
            }
            set
            {
                OnBasicTraffic_DescriptionChanging(value);
                ReportPropertyChanging("BasicTraffic_Description");
                _BasicTraffic_Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BasicTraffic_Description");
                OnBasicTraffic_DescriptionChanged();
            }
        }
        private global::System.String _BasicTraffic_Description;
        partial void OnBasicTraffic_DescriptionChanging(global::System.String value);
        partial void OnBasicTraffic_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BasicTraffic_ClockCustomCode
        {
            get
            {
                return _BasicTraffic_ClockCustomCode;
            }
            set
            {
                OnBasicTraffic_ClockCustomCodeChanging(value);
                ReportPropertyChanging("BasicTraffic_ClockCustomCode");
                _BasicTraffic_ClockCustomCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BasicTraffic_ClockCustomCode");
                OnBasicTraffic_ClockCustomCodeChanged();
            }
        }
        private global::System.String _BasicTraffic_ClockCustomCode;
        partial void OnBasicTraffic_ClockCustomCodeChanging(global::System.String value);
        partial void OnBasicTraffic_ClockCustomCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> BasicTraffic_Transferred
        {
            get
            {
                return _BasicTraffic_Transferred;
            }
            set
            {
                OnBasicTraffic_TransferredChanging(value);
                ReportPropertyChanging("BasicTraffic_Transferred");
                _BasicTraffic_Transferred = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BasicTraffic_Transferred");
                OnBasicTraffic_TransferredChanged();
            }
        }
        private Nullable<global::System.Boolean> _BasicTraffic_Transferred;
        partial void OnBasicTraffic_TransferredChanging(Nullable<global::System.Boolean> value);
        partial void OnBasicTraffic_TransferredChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FalatGTSModel", "FK_TA_BaseTrafic_TA_Person", "TA_Person")]
        public TA_Person TA_Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_Person>("FalatGTSModel.FK_TA_BaseTrafic_TA_Person", "TA_Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_Person>("FalatGTSModel.FK_TA_BaseTrafic_TA_Person", "TA_Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TA_Person> TA_PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_Person>("FalatGTSModel.FK_TA_BaseTrafic_TA_Person", "TA_Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TA_Person>("FalatGTSModel.FK_TA_BaseTrafic_TA_Person", "TA_Person", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FalatGTSModel", Name="TA_Calculation_Flag_Persons")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TA_Calculation_Flag_Persons : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TA_Calculation_Flag_Persons object.
        /// </summary>
        /// <param name="cFP_ID">Initial value of the CFP_ID property.</param>
        /// <param name="cFP_PrsId">Initial value of the CFP_PrsId property.</param>
        /// <param name="cFP_Date">Initial value of the CFP_Date property.</param>
        public static TA_Calculation_Flag_Persons CreateTA_Calculation_Flag_Persons(global::System.Decimal cFP_ID, global::System.Decimal cFP_PrsId, global::System.DateTime cFP_Date)
        {
            TA_Calculation_Flag_Persons tA_Calculation_Flag_Persons = new TA_Calculation_Flag_Persons();
            tA_Calculation_Flag_Persons.CFP_ID = cFP_ID;
            tA_Calculation_Flag_Persons.CFP_PrsId = cFP_PrsId;
            tA_Calculation_Flag_Persons.CFP_Date = cFP_Date;
            return tA_Calculation_Flag_Persons;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CFP_ID
        {
            get
            {
                return _CFP_ID;
            }
            set
            {
                if (_CFP_ID != value)
                {
                    OnCFP_IDChanging(value);
                    ReportPropertyChanging("CFP_ID");
                    _CFP_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CFP_ID");
                    OnCFP_IDChanged();
                }
            }
        }
        private global::System.Decimal _CFP_ID;
        partial void OnCFP_IDChanging(global::System.Decimal value);
        partial void OnCFP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CFP_PrsId
        {
            get
            {
                return _CFP_PrsId;
            }
            set
            {
                OnCFP_PrsIdChanging(value);
                ReportPropertyChanging("CFP_PrsId");
                _CFP_PrsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CFP_PrsId");
                OnCFP_PrsIdChanged();
            }
        }
        private global::System.Decimal _CFP_PrsId;
        partial void OnCFP_PrsIdChanging(global::System.Decimal value);
        partial void OnCFP_PrsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CFP_Date
        {
            get
            {
                return _CFP_Date;
            }
            set
            {
                OnCFP_DateChanging(value);
                ReportPropertyChanging("CFP_Date");
                _CFP_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CFP_Date");
                OnCFP_DateChanged();
            }
        }
        private global::System.DateTime _CFP_Date;
        partial void OnCFP_DateChanging(global::System.DateTime value);
        partial void OnCFP_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CFP_MidNightCalculate
        {
            get
            {
                return _CFP_MidNightCalculate;
            }
            set
            {
                OnCFP_MidNightCalculateChanging(value);
                ReportPropertyChanging("CFP_MidNightCalculate");
                _CFP_MidNightCalculate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CFP_MidNightCalculate");
                OnCFP_MidNightCalculateChanged();
            }
        }
        private Nullable<global::System.Boolean> _CFP_MidNightCalculate;
        partial void OnCFP_MidNightCalculateChanging(Nullable<global::System.Boolean> value);
        partial void OnCFP_MidNightCalculateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CFP_CalculationIsValid
        {
            get
            {
                return _CFP_CalculationIsValid;
            }
            set
            {
                OnCFP_CalculationIsValidChanging(value);
                ReportPropertyChanging("CFP_CalculationIsValid");
                _CFP_CalculationIsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CFP_CalculationIsValid");
                OnCFP_CalculationIsValidChanged();
            }
        }
        private Nullable<global::System.Boolean> _CFP_CalculationIsValid;
        partial void OnCFP_CalculationIsValidChanging(Nullable<global::System.Boolean> value);
        partial void OnCFP_CalculationIsValidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FalatGTSModel", "FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Person")]
        public TA_Person TA_Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_Person>("FalatGTSModel.FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_Person>("FalatGTSModel.FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TA_Person> TA_PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_Person>("FalatGTSModel.FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TA_Person>("FalatGTSModel.FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Person", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FalatGTSModel", Name="TA_NeedUpdateCFP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TA_NeedUpdateCFP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TA_NeedUpdateCFP object.
        /// </summary>
        /// <param name="personId">Initial value of the PersonId property.</param>
        public static TA_NeedUpdateCFP CreateTA_NeedUpdateCFP(global::System.Decimal personId)
        {
            TA_NeedUpdateCFP tA_NeedUpdateCFP = new TA_NeedUpdateCFP();
            tA_NeedUpdateCFP.PersonId = personId;
            return tA_NeedUpdateCFP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                if (_PersonId != value)
                {
                    OnPersonIdChanging(value);
                    ReportPropertyChanging("PersonId");
                    _PersonId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PersonId");
                    OnPersonIdChanged();
                }
            }
        }
        private global::System.Decimal _PersonId;
        partial void OnPersonIdChanging(global::System.Decimal value);
        partial void OnPersonIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FalatGTSModel", Name="TA_Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TA_Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TA_Person object.
        /// </summary>
        /// <param name="prs_ID">Initial value of the Prs_ID property.</param>
        public static TA_Person CreateTA_Person(global::System.Decimal prs_ID)
        {
            TA_Person tA_Person = new TA_Person();
            tA_Person.Prs_ID = prs_ID;
            return tA_Person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Prs_ID
        {
            get
            {
                return _Prs_ID;
            }
            set
            {
                if (_Prs_ID != value)
                {
                    OnPrs_IDChanging(value);
                    ReportPropertyChanging("Prs_ID");
                    _Prs_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Prs_ID");
                    OnPrs_IDChanged();
                }
            }
        }
        private global::System.Decimal _Prs_ID;
        partial void OnPrs_IDChanging(global::System.Decimal value);
        partial void OnPrs_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_Barcode
        {
            get
            {
                return _Prs_Barcode;
            }
            set
            {
                OnPrs_BarcodeChanging(value);
                ReportPropertyChanging("Prs_Barcode");
                _Prs_Barcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_Barcode");
                OnPrs_BarcodeChanged();
            }
        }
        private global::System.String _Prs_Barcode;
        partial void OnPrs_BarcodeChanging(global::System.String value);
        partial void OnPrs_BarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Prs__Param
        {
            get
            {
                return _Prs__Param;
            }
            set
            {
                OnPrs__ParamChanging(value);
                ReportPropertyChanging("Prs__Param");
                _Prs__Param = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs__Param");
                OnPrs__ParamChanged();
            }
        }
        private Nullable<global::System.Int32> _Prs__Param;
        partial void OnPrs__ParamChanging(Nullable<global::System.Int32> value);
        partial void OnPrs__ParamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Prs_Active
        {
            get
            {
                return _Prs_Active;
            }
            set
            {
                OnPrs_ActiveChanging(value);
                ReportPropertyChanging("Prs_Active");
                _Prs_Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_Active");
                OnPrs_ActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Prs_Active;
        partial void OnPrs_ActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnPrs_ActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_CardNum
        {
            get
            {
                return _Prs_CardNum;
            }
            set
            {
                OnPrs_CardNumChanging(value);
                ReportPropertyChanging("Prs_CardNum");
                _Prs_CardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_CardNum");
                OnPrs_CardNumChanged();
            }
        }
        private global::System.String _Prs_CardNum;
        partial void OnPrs_CardNumChanging(global::System.String value);
        partial void OnPrs_CardNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_DepartmentId
        {
            get
            {
                return _Prs_DepartmentId;
            }
            set
            {
                OnPrs_DepartmentIdChanging(value);
                ReportPropertyChanging("Prs_DepartmentId");
                _Prs_DepartmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_DepartmentId");
                OnPrs_DepartmentIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_DepartmentId;
        partial void OnPrs_DepartmentIdChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_DepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_EmploymentNum
        {
            get
            {
                return _Prs_EmploymentNum;
            }
            set
            {
                OnPrs_EmploymentNumChanging(value);
                ReportPropertyChanging("Prs_EmploymentNum");
                _Prs_EmploymentNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_EmploymentNum");
                OnPrs_EmploymentNumChanged();
            }
        }
        private global::System.String _Prs_EmploymentNum;
        partial void OnPrs_EmploymentNumChanging(global::System.String value);
        partial void OnPrs_EmploymentNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Prs_EmploymentDate
        {
            get
            {
                return _Prs_EmploymentDate;
            }
            set
            {
                OnPrs_EmploymentDateChanging(value);
                ReportPropertyChanging("Prs_EmploymentDate");
                _Prs_EmploymentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_EmploymentDate");
                OnPrs_EmploymentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Prs_EmploymentDate;
        partial void OnPrs_EmploymentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPrs_EmploymentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Prs_EndEmploymentDate
        {
            get
            {
                return _Prs_EndEmploymentDate;
            }
            set
            {
                OnPrs_EndEmploymentDateChanging(value);
                ReportPropertyChanging("Prs_EndEmploymentDate");
                _Prs_EndEmploymentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_EndEmploymentDate");
                OnPrs_EndEmploymentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Prs_EndEmploymentDate;
        partial void OnPrs_EndEmploymentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPrs_EndEmploymentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_EmployId
        {
            get
            {
                return _Prs_EmployId;
            }
            set
            {
                OnPrs_EmployIdChanging(value);
                ReportPropertyChanging("Prs_EmployId");
                _Prs_EmployId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_EmployId");
                OnPrs_EmployIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_EmployId;
        partial void OnPrs_EmployIdChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_EmployIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Prs_Sex
        {
            get
            {
                return _Prs_Sex;
            }
            set
            {
                OnPrs_SexChanging(value);
                ReportPropertyChanging("Prs_Sex");
                _Prs_Sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_Sex");
                OnPrs_SexChanged();
            }
        }
        private Nullable<global::System.Boolean> _Prs_Sex;
        partial void OnPrs_SexChanging(Nullable<global::System.Boolean> value);
        partial void OnPrs_SexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_Education
        {
            get
            {
                return _Prs_Education;
            }
            set
            {
                OnPrs_EducationChanging(value);
                ReportPropertyChanging("Prs_Education");
                _Prs_Education = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_Education");
                OnPrs_EducationChanged();
            }
        }
        private global::System.String _Prs_Education;
        partial void OnPrs_EducationChanging(global::System.String value);
        partial void OnPrs_EducationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_FirstName
        {
            get
            {
                return _Prs_FirstName;
            }
            set
            {
                OnPrs_FirstNameChanging(value);
                ReportPropertyChanging("Prs_FirstName");
                _Prs_FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_FirstName");
                OnPrs_FirstNameChanged();
            }
        }
        private global::System.String _Prs_FirstName;
        partial void OnPrs_FirstNameChanging(global::System.String value);
        partial void OnPrs_FirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Prs_MaritalStatus
        {
            get
            {
                return _Prs_MaritalStatus;
            }
            set
            {
                OnPrs_MaritalStatusChanging(value);
                ReportPropertyChanging("Prs_MaritalStatus");
                _Prs_MaritalStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_MaritalStatus");
                OnPrs_MaritalStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Prs_MaritalStatus;
        partial void OnPrs_MaritalStatusChanging(Nullable<global::System.Int32> value);
        partial void OnPrs_MaritalStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_LastName
        {
            get
            {
                return _Prs_LastName;
            }
            set
            {
                OnPrs_LastNameChanging(value);
                ReportPropertyChanging("Prs_LastName");
                _Prs_LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_LastName");
                OnPrs_LastNameChanged();
            }
        }
        private global::System.String _Prs_LastName;
        partial void OnPrs_LastNameChanging(global::System.String value);
        partial void OnPrs_LastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_PrsDtlID
        {
            get
            {
                return _Prs_PrsDtlID;
            }
            set
            {
                OnPrs_PrsDtlIDChanging(value);
                ReportPropertyChanging("Prs_PrsDtlID");
                _Prs_PrsDtlID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_PrsDtlID");
                OnPrs_PrsDtlIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_PrsDtlID;
        partial void OnPrs_PrsDtlIDChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_PrsDtlIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> prs_IsDeleted
        {
            get
            {
                return _prs_IsDeleted;
            }
            set
            {
                Onprs_IsDeletedChanging(value);
                ReportPropertyChanging("prs_IsDeleted");
                _prs_IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prs_IsDeleted");
                Onprs_IsDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _prs_IsDeleted;
        partial void Onprs_IsDeletedChanging(Nullable<global::System.Boolean> value);
        partial void Onprs_IsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> prs_CreationDate
        {
            get
            {
                return _prs_CreationDate;
            }
            set
            {
                Onprs_CreationDateChanging(value);
                ReportPropertyChanging("prs_CreationDate");
                _prs_CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prs_CreationDate");
                Onprs_CreationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _prs_CreationDate;
        partial void Onprs_CreationDateChanging(Nullable<global::System.DateTime> value);
        partial void Onprs_CreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_GradeID
        {
            get
            {
                return _Prs_GradeID;
            }
            set
            {
                OnPrs_GradeIDChanging(value);
                ReportPropertyChanging("Prs_GradeID");
                _Prs_GradeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_GradeID");
                OnPrs_GradeIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_GradeID;
        partial void OnPrs_GradeIDChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_GradeIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FalatGTSModel", "FK_TA_BaseTrafic_TA_Person", "TA_BaseTraffic")]
        public EntityCollection<TA_BaseTraffic> TA_BaseTraffic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TA_BaseTraffic>("FalatGTSModel.FK_TA_BaseTrafic_TA_Person", "TA_BaseTraffic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TA_BaseTraffic>("FalatGTSModel.FK_TA_BaseTrafic_TA_Person", "TA_BaseTraffic", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FalatGTSModel", "FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Calculation_Flag_Persons")]
        public EntityCollection<TA_Calculation_Flag_Persons> TA_Calculation_Flag_Persons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TA_Calculation_Flag_Persons>("FalatGTSModel.FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Calculation_Flag_Persons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TA_Calculation_Flag_Persons>("FalatGTSModel.FK_TA_Calculation_Flag_Persons_TA_Person", "TA_Calculation_Flag_Persons", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
